name: Deploy to EC2

on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때마다 배포

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VITE_BACK_URL: ${{ secrets.VITE_BACK_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.13.1'

      - name: Install dependencies
        run: |
          yarn install

      - name: Build the project
        run: |
          yarn build  # 빌드 결과물을 생성

      - name: Upload build files to EC2
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }} # EC2 IP 주소
          username: ${{ secrets.EC2_USERNAME }} # EC2 사용자 이름 (예: ec2-user, ubuntu)
          key: ${{ secrets.EC2_SSH_KEY }} # EC2 SSH 키 (Private Key)
          source: 'dist/*' # 빌드된 파일들
          target: '/home/ubuntu/dist' # EC2의 Nginx 웹 서버 디렉토리

      - name: Restart Nginx on EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }} # EC2 IP 주소
          username: ${{ secrets.EC2_USERNAME }} # EC2 사용자 이름 (예: ec2-user, ubuntu)
          key: ${{ secrets.EC2_SSH_KEY }} # EC2 SSH 키 (Private Key)
          script: |
            sudo rm -rf /var/www/frontend/*
            sudo mv -f /home/ubuntu/dist/* /var/www/frontend/  # 일반 사용자 디렉토리에서 Nginx가 있는 디렉토리로 파일 이동
            sudo chown -R www-data:www-data /var/www/frontend  # Nginx 사용자 권한으로 변경
            sudo systemctl restart nginx  # Nginx 서버 재시작
